#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += s5kjn1sq03mipiraw_Sensor.o
# Antaiui <AI_BSP_CAM> <danyangwei> <2022-01-22> move to mtk arch begin
#obj-y += s5kjn1sq03_eeprom.o
# Antaiui <AI_BSP_CAM> <danyangwei> <2022-01-22> move to mtk arch end
